### ISSUE TITLE
500 error on edit permission

### ISSUE THREAD

**Issue by mblomdahl** [libris/xl_auth#76]
Postgres syntax error when submitting a permission edit request:

```
2017-10-25T14:41:41.807334596Z  [2017-10-25 14:41:41,806] ERROR in app: Exception on /permissions/edit/1511 [POST]
2017-10-25T14:41:41.807358654Z  Traceback (most recent call last):
2017-10-25T14:41:41.807364083Z    File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
2017-10-25T14:41:41.807368376Z      context)
2017-10-25T14:41:41.807371616Z    File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
2017-10-25T14:41:41.807375111Z      cursor.execute(statement, parameters)
2017-10-25T14:41:41.807378280Z  psycopg2.ProgrammingError: syntax error at or near "1511"
2017-10-25T14:41:41.807381764Z  LINE 3: WHERE permissions.id IS NOT 1511 AND permissions.user_id = 4...
2017-10-25T14:41:41.807384940Z                                      ^
2017-10-25T14:41:41.807388053Z  
2017-10-25T14:41:41.807398573Z  
2017-10-25T14:41:41.807402183Z  The above exception was the direct cause of the following exception:
2017-10-25T14:41:41.807405474Z  
2017-10-25T14:41:41.807408328Z  Traceback (most recent call last):
2017-10-25T14:41:41.807411456Z    File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
2017-10-25T14:41:41.807414823Z      response = self.full_dispatch_request()
2017-10-25T14:41:41.807417893Z    File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
2017-10-25T14:41:41.807421281Z      rv = self.handle_user_exception(e)
2017-10-25T14:41:41.807424358Z    File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
2017-10-25T14:41:41.807427607Z      reraise(exc_type, exc_value, tb)
2017-10-25T14:41:41.807430508Z    File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
2017-10-25T14:41:41.807433624Z      raise value
2017-10-25T14:41:41.807449133Z    File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
2017-10-25T14:41:41.807453335Z      rv = self.dispatch_request()
2017-10-25T14:41:41.807456621Z    File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
2017-10-25T14:41:41.807459993Z      return self.view_functions[rule.endpoint](**req.view_args)
2017-10-25T14:41:41.807463028Z    File "/usr/local/lib/python3.6/site-packages/flask_login/utils.py", line 228, in decorated_view
2017-10-25T14:41:41.807466408Z      return func(*args, **kwargs)
2017-10-25T14:41:41.807469360Z    File "/xl_auth/xl_auth/permission/views.py", line 66, in edit
2017-10-25T14:41:41.807481955Z      if edit_permission_form.validate_on_submit():
2017-10-25T14:41:41.807485741Z    File "/usr/local/lib/python3.6/site-packages/flask_wtf/form.py", line 101, in validate_on_submit
2017-10-25T14:41:41.807493140Z      return self.is_submitted() and self.validate()
2017-10-25T14:41:41.807496454Z    File "/xl_auth/xl_auth/permission/forms.py", line 110, in validate
2017-10-25T14:41:41.807499811Z      user_id=self.user_id.data, collection_id=self.collection_id.data).first()
2017-10-25T14:41:41.807504140Z    File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2755, in first
2017-10-25T14:41:41.807507580Z      ret = list(self[0:1])
2017-10-25T14:41:41.807510617Z    File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2547, in __getitem__
2017-10-25T14:41:41.807513945Z      return list(res)
2017-10-25T14:41:41.807516892Z    File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
2017-10-25T14:41:41.807520198Z      return self._execute_and_instances(context)
2017-10-25T14:41:41.807523191Z    File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2878, in _execute_and_instances
2017-10-25T14:41:41.807526641Z      result = conn.execute(querycontext.statement, self._params)
2017-10-25T14:41:41.807529652Z    File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 945, in execute
2017-10-25T14:41:41.807532832Z      return meth(self, multiparams, params)
2017-10-25T14:41:41.807535794Z    File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
2017-10-25T14:41:41.807539095Z      return connection._execute_clauseelement(self, multiparams, params)
2017-10-25T14:41:41.807542155Z    File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
2017-10-25T14:41:41.807545478Z      compiled_sql, distilled_params
2017-10-25T14:41:41.807548394Z    File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
2017-10-25T14:41:41.807551705Z      context)
2017-10-25T14:41:41.807554587Z    File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
2017-10-25T14:41:41.807557995Z      exc_info
2017-10-25T14:41:41.807560860Z    File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
2017-10-25T14:41:41.807564134Z      reraise(type(exception), exception, tb=exc_tb, cause=cause)
2017-10-25T14:41:41.807567288Z    File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
2017-10-25T14:41:41.807570488Z      raise value.with_traceback(tb)
2017-10-25T14:41:41.807573388Z    File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
2017-10-25T14:41:41.807579485Z      context)
2017-10-25T14:41:41.807582714Z    File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
2017-10-25T14:41:41.807586041Z      cursor.execute(statement, parameters)
2017-10-25T14:41:41.807589055Z  sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) syntax error at or near "1511"
2017-10-25T14:41:41.807592274Z  LINE 3: WHERE permissions.id IS NOT 1511 AND permissions.user_id = 4...
2017-10-25T14:41:41.807595392Z                                      ^
2017-10-25T14:41:41.807598829Z   [SQL: 'SELECT permissions.id AS permissions_id, permissions.user_id AS permissions_user_id, permissions.collection_id AS permissions_collection_id, permissions.registrant AS permissions_registrant, permissions.cataloger AS permissions_cataloger, permissions.cataloging_admin AS permissions_cataloging_admin, permissions.created_at AS permissions_created_at \nFROM permissions \nWHERE permissions.id IS NOT %(id_1)s AND permissions.user_id = %(user_id_1)s AND permissions.collection_id = %(collection_id_1)s \n LIMIT %(param_1)s'] [parameters: {'id_1': 1511, 'user_id_1': 402, 'collection_id_1': 344, 'param_1': 1}]
2017-10-25T14:41:41.811461704Z  172.17.0.1 - - [25/Oct/2017 14:41:41] "POST /permissions/edit/1511 HTTP/1.0" 500 -
```

**Comment by mblomdahl** [comment]
@mxtthias Being good at Postgres and stuff... Any idea what to make of this?
